{
 "title": "Performance",
 "time": { "from": "2020-08-29T00:30:58.138Z", "to": "2021-01-02T22:02:10.495Z" },
 "templating": {
  "list": [
   {
    "name": "model_name",
    "label": "Model",
    "query": "select distinct name from model"
   },
   {
    "name": "model_id",
    "query": "select id from model where model.name = '$model_name'"
   },
   {
    "name": "metric_name",
    "label": "Metric",
    "query": "select distinct metric_name from realized_performance_metrics where model_id = $model_id"
   }
  ]
 },
 "panels": [
  {
   "title": "Realized ROC AUC Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'roc_auc'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Realized F1 Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'f1'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Realized Precision Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'precision'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Realized Recall Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'recall'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Realized Specificity Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'specificity'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Realized Accuracy Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'accuracy'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Estimated ROC AUC Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM cbpe_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'roc_auc'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Estimated F1 Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM cbpe_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'f1'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Estimated Precision Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM cbpe_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'precision'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Estimated Recall Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM cbpe_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'recall'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Estimated Specificity Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM cbpe_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'specificity'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Estimated Accuracy Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM cbpe_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'accuracy'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Realized Performance - $metric_name",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metric_name AS metric,\n  value\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$metric_name'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metric_name AS metric,\n  lower_threshold,\n  upper_threshold\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$metric_name'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  alert\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$metric_name'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Estimated performance (CBPE) - $metric_name",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metric_name AS metric,\n  value\nFROM cbpe_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$metric_name'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metric_name AS metric,\n  lower_threshold,\n  upper_threshold\nFROM cbpe_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$metric_name'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  alert\nFROM cbpe_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$metric_name'\nORDER BY 1"
    }
   ]
  }
 ]
}