{
 "title": "Drift",
 "time": { "from": "2018-09-29T15:50:11.382Z", "to": "2019-05-15T22:01:43.885Z" },
 "templating": {
  "list": [
   {
    "name": "model_name",
    "label": "Model",
    "query": "select distinct name from model"
   },
   {
    "name": "model_id",
    "query": "select id from model where model.name = '${model_name}'"
   },
   {
    "name": "feature_names",
    "label": "Features",
    "query": "select distinct feature_name from statistical_feature_drift_metrics  where model_id=${model_id}"
   }
  ]
 },
 "panels": [
  {
   "title": "Statistical Feature Drift Alerts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM statistical_feature_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  feature_name IN ($feature_names)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Reconstruction Error Drift Alerts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM data_reconstruction_feature_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Statistical Model Prediction Drift Alerts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM statistical_output_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  output_name = 'y_pred'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Statistical Model Score Drift Alerts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM statistical_output_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  output_name = 'y_pred_proba'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Statistical Target Drift Alerts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM target_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  { "title": "Model inputs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Univariate Feature Drift: ${feature_names}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metric_name AS metric,\n  value,\n  feature_name\nFROM statistical_feature_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  feature_name IN ($feature_names)\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  alert\nFROM statistical_feature_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  feature_name IN ($feature_names)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Multivariate Drift - Reconstruction Error (PCA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metric_name AS metric,\n  value\nFROM data_reconstruction_feature_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  lower_threshold,\n  upper_threshold\nFROM data_reconstruction_feature_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  alert\nFROM data_reconstruction_feature_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id\nORDER BY 1"
    }
   ]
  },
  { "title": "Model outputs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metric_name AS metric,\n  value\nFROM statistical_output_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  output_name = 'y_pred'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  alert\nFROM statistical_output_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  output_name = 'y_pred'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Score Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metric_name AS metric,\n  value\nFROM statistical_output_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  output_name = 'y_pred_proba'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  alert\nFROM statistical_output_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  output_name = 'y_pred_proba'\nORDER BY 1"
    }
   ]
  },
  { "title": "Model targets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Target Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metric_name AS metric,\n  value\nFROM target_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  alert\nFROM target_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id\nORDER BY 1"
    }
   ]
  }
 ]
}