{
 "title": "Performance",
 "time": { "from": "2017-01-26T12:24:22.877Z", "to": "2017-03-15T06:13:01.335Z" },
 "templating": {
  "list": [
   {
    "name": "model_name",
    "label": "Model",
    "query": "select distinct name from model"
   },
   {
    "name": "model_id",
    "query": "select id from model where model.name = '$model_name'"
   },
   {
    "name": "metric_name",
    "label": "Metric",
    "query": "select distinct metric_name from realized_performance_metrics where model_id = $model_id"
   }
  ]
 },
 "panels": [
  {
   "title": "Realized MAE Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'MAE'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Realized MAPE Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'MAPE'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Realized MSE Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'MSE'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Realized MSLE Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'MSLE'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Realized RMSE Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'RMSE'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Realized RMSLE Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'RMSLE'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Estimated MAE Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM dle_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'MAE'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Estimated MAPE Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM dle_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'MAPE'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Estimated MSE Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM dle_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'MSE'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Estimated MSLE Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM dle_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'MSLE'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Estimated RMSE Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM dle_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'RMSE'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Estimated RMSLE Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM dle_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND \n  metric_name = 'RMSLE'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Realized Performance - $metric_name",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metric_name AS metric,\n  value\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$metric_name'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metric_name AS metric,\n  lower_threshold,\n  upper_threshold\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$metric_name'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  alert\nFROM realized_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$metric_name'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Estimated performance (DLE) - $metric_name",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metric_name AS metric,\n  value\nFROM dle_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$metric_name'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metric_name AS metric,\n  lower_threshold,\n  upper_threshold\nFROM dle_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$metric_name'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  alert\nFROM dle_performance_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$metric_name'\nORDER BY 1"
    }
   ]
  }
 ]
}