input:
  reference_data:
    path: /data/regression_synthetic_reference.csv

  analysis_data:
    path: /data/regression_synthetic_analysis.csv

  target_data:
    path: /data/regression_synthetic_analysis_targets.csv

output:
  database:
    connection_string: postgresql://nannyml:we<3nannyml@metrics-store:5432/nannyml
    model_name: car_price_regression

problem_type: regression

chunker:
  chunk_period: D

store:
  file:
    path: /store

column_mapping:
  features:
    - car_age
    - km_driven
    - price_new
    - accident_count
    - door_count
    - transmission
    - fuel
  timestamp: timestamp
  y_pred: y_pred
  y_true: y_true
