{
 "title": "Drift",
 "time": { "from": "2017-02-15T15:54:40.731Z", "to": "2017-03-12T21:59:51.930Z" },
 "templating": {
  "list": [
   {
    "name": "model_name",
    "label": "Model",
    "query": "select distinct name from model"
   },
   {
    "name": "model_id",
    "query": "select id from model where model.name = '${model_name}'"
   },
   {
    "name": "column_names",
    "label": "Column names",
    "query": "select distinct column_name from univariate_drift_metrics  where model_id=${model_id}"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "select distinct metric_name from univariate_drift_metrics  where model_id=${model_id}"
   }
  ]
 },
 "panels": [
  {
   "title": "Drift Alerts",
   "type": "stat",
   "description": "Drift alerts for ${column_names} for method ${method}",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM univariate_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$method' AND\n  column_name IN ($column_names)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Reconstruction Error Drift Alerts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM data_reconstruction_feature_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Model Prediction Drift Alerts",
   "type": "stat",
   "description": "Number of alerts for model prediction for method ${method}",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM univariate_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$method' AND\n  column_name = 'y_pred'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Target Drift Alerts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(*) FILTER (WHERE alert) AS \"alert\"\nFROM univariate_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$method' AND\n  column_name = 'y_true'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  { "title": "Model inputs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Univariate Drift: ${column_names} [$method]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value,\n  column_name\nFROM univariate_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  column_name IN ($column_names) AND\n  metric_name = '$method'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  alert\nFROM univariate_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  column_name IN ($column_names) AND\n  metric_name = '$method'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Multivariate Drift - Reconstruction Error (PCA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metric_name AS metric,\n  value\nFROM data_reconstruction_feature_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  lower_threshold,\n  upper_threshold\nFROM data_reconstruction_feature_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  alert\nFROM data_reconstruction_feature_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id\nORDER BY 1"
    }
   ]
  },
  { "title": "Model output and target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value\nFROM univariate_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$method' AND\n  column_name = 'y_pred'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  alert\nFROM univariate_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$method' AND\n  column_name = 'y_pred'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Target Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metric_name AS metric,\n  value\nFROM univariate_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$method' AND\n  column_name = 'y_true'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  alert\nFROM univariate_drift_metrics\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  model_id = $model_id AND\n  metric_name = '$method' AND \n  column_name = 'y_true'\nORDER BY 1"
    }
   ]
  }
 ]
}